drop user INFINYS_CMS cascade;
drop user MIGRATION_SST3_POST cascade;
drop user MIGRATION_SST_POST  cascade;        
drop user MIGRATION  cascade;         
drop user AWCC_DDS_SST  cascade;                  
drop user AWCC_DDS_CORE  cascade;               
drop user EBOS_APPL  cascade;
drop user COLL_APPL  cascade;  
drop user OPENCMS cascade;
drop user JETSPEED cascade;
drop user WSC cascade;
drop user IAM_USER cascade;
drop user CUSTOM_CYGENT_ADMIN cascade;     
drop user CUSTOM_OFM_ADMIN cascade;
drop user CUSTOM_ECA_ADMIN cascade;
drop user ECA_CUSTOM cascade;
drop user cricket_custom_om cascade;        
drop user cricket_custom_rb cascade;                                           
drop user cricket_custom_api cascade;
drop user custom_rb cascade;
drop user RB_CUSTOM cascade; 
drop user COLL_ADMIN cascade;        
drop user CBL_ADMIN cascade;                                                   
drop user CSM_ADMIN cascade;                                                   
drop user CYGENT_ADMIN cascade;                                                
drop user DUKE_ADMIN cascade;                                                  
drop user GENEVAADMINUSER cascade;                                             
drop user GENEVABATCHUSER cascade;                                             
drop user GENEVA_ADMIN cascade;                                                
drop user INF_ADMIN cascade;        
drop user NII_ADMIN cascade;        
drop user IPFAPPUSER cascade;                                                  
drop user IPF_ADMIN cascade;                                                   
drop user IPF_AUDIT_ADMIN cascade;                                             
drop user IPF_SEC_ADMIN cascade;                                               
drop user SECURITY cascade;                                                    
drop user UNIF_ADMIN cascade;                                                  
drop user OFM_ADMIN  cascade;
drop user GENEVASYSMONVIEWUSER  cascade;
drop user GENEVASYSMONMAINTUSER  cascade;
drop user GENEVASYSCONVIEWUSER  cascade;
drop user GENEVASYSCONSUPERUSER   cascade;
drop user GENEVASYSCONMAINTUSER  cascade;
drop user GENEVARECVIEWUSER  cascade;
drop user GENEVARECMAINTUSER  cascade;
drop user GENEVARATVIEWUSER  cascade;
drop user GENEVARATPUBUSER   cascade;
drop user GENEVAPRODVIEWUSER  cascade;
drop user GENEVAPRODMAINTUSER  cascade;
drop user GENEVAPAYPOSTUSER  cascade;
drop user GENEVAPAYENTRYUSER  cascade;
drop user GENEVAECAUSER  cascade;
drop user GENEVACATVIEWUSER  cascade;
drop user GENEVACATPUBUSER  cascade;
drop user GENEVACATMAINTUSER cascade;
drop user GENEVAACCVIEWUSER  cascade;
drop user GENEVAACCMAINTUSER cascade;
drop user GENEVARATMAINTUSER cascade;
drop role INFINYS_CMS;
drop role IAM_USER;
drop role CRICKET_CUSTOM_OM_ADMIN;
drop role CRICKET_CUSTOM_RB_ADMIN;
drop role CRICKET_CUSTOM_API_ADMIN;
drop role INFINYS_IM;     
drop role INFINYS_CSM;     
drop role INFINYS_CSM_ADMIN;
drop role GENEVA_ADMIN;
drop role GENEVAADMIN;                                                         
drop role GENEVAAPP;                                                           
drop role GENEVABATCH;                                                         
drop role GENEVAPUBLIC;                                                        
drop role GENEVASECURITY;                                                      
drop role GENEVAVERSION;                                                       
drop role INFINYS_PF;                                                          
drop role INFINYS_PUBLIC_INSTALL;                    
drop role INFINYS_PUBLIC;
drop role INFINYS_RB;                                                          
drop role PF_AUDIT_ADMIN_IPF_AUDIT_ADMIN;                                      
drop role PF_AUDIT_IPF_AUDIT_ADMIN;                                            
drop role PF_AUDIT_READ_IPF_AUDIT_ADMIN;                                       
drop role PF_READ_ONLY_ROLE_UNIF_ADMIN;                                        
drop role PF_UPDATE_ROLE_UNIF_ADMIN;                                           
drop role INFINYS_CYGENT_ADMIN;          
drop role INFINYS_OFM_ADMIN;             
drop role COLLECTIONS_EBOS_ROLE;     
drop role COLLECTIONS_EBOS_S_ROLE;
drop role EBOS_ROLE;      
drop role EBOS_S_ROLE;                   
drop role COLLECTIONS_ROLE;              
drop role COLLECTIONS_S_ROLE;      
drop role GVIADMIN;
drop role GVIBATCH;           
drop role GVIUSER;     
