
drop sequence ACCOUNTNUMSEQ ;                                                                                                                                                   
drop sequence AEGSEQ ;                                                                                                                                                          
drop sequence AQ$_COSTEDEVENTQUEUEHEAD_N ;                                                                                                                                      
drop sequence AQ$_COSTEDEVENTQUEUETAIL_N ;                                                                                                                                      
drop sequence AQ$_REJECTEVENTQUEUEHEAD_N ;                                                                                                                                      
drop sequence AQ$_REJECTEVENTQUEUETAIL_N ;                                                                                                                                      
drop sequence AUTHCODESEQ ;                                                                                                                                                     
drop sequence BANDINGMODELIDSEQ ;                                                                                                                                               
drop sequence BATCHIDSEQ ;                                                                                                                                                      
drop sequence BILLDISCOUNTIDSEQ ;                                                                                                                                               
drop sequence BILLINGARCHIVEFILENUMSEQ ;                                                                                                                                        
drop sequence BILLINGCONFLICTSEQ ;                                                                                                                                              
drop sequence BILLINGEDITSEQ ;                                                                                                                                                  

drop sequence BILLINGEXPORTSEQ ;                                                                                                                                                
drop sequence BILLINGIMPORTSEQ ;                                                                                                                                                
drop sequence BONUSSCHEMEIDSEQ ;                                                                                                                                                
drop sequence BUDGETPAYPLANIDSEQ ;                                                                                                                                              
drop sequence CCMANDATESEQ ;                                                                                                                                                    
drop sequence CHARGESEGMENTIDSEQ ;                                                                                                                                              
drop sequence COMPOSITEFILTERIDSEQ ;                                                                                                                                            
drop sequence CONVERGYSDPCVERIFICATION ;                                                                                                                                        
drop sequence COSTBANDIDSEQ ;                                                                                                                                                   
drop sequence COSTGROUPIDSEQ ;                                                                                                                                                  
drop sequence COSTINGRULESIDSEQ ;                                                                                                                                               
drop sequence CUSTOMERREFSEQ ;                                                                                                                                                  
drop sequence DDMANDATESEQ ;                                                                                                                                                    

drop sequence DISPATCHAUDIT_SEQ ;                                                                                                                                               
drop sequence DLFBATCHSEQ ;                                                                                                                                                     
drop sequence DUNNINGARCHIVEFILENUMSEQ ;                                                                                                                                        
drop sequence ECAINCIDENTGROUPSEQ ;                                                                                                                                             
drop sequence EVENTCLASSIDSEQ ;                                                                                                                                                 
drop sequence EVENTDISCOUNTIDSEQ ;                                                                                                                                              
drop sequence EVENTFILTERIDSEQ ;                                                                                                                                                
drop sequence GC_PRODCUST10001SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10002SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10003SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10004SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10005SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10006SEQ ;                                                                                                                                             

drop sequence GC_PRODCUST10007SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10008SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10009SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10014SEQ ;                                                                                                                                             
drop sequence GC_PRODCUST10015SEQ ;                                                                                                                                             
drop sequence ICEUNSETCARRYGROUPRUNIDSEQ ;                                                                                                                                      
drop sequence JOBIDSEQ ;                                                                                                                                                        
drop sequence LOCKVERSIONSEQ ;                                                                                                                                                  
drop sequence MANAGEDFILEIDSEQ ;                                                                                                                                                
drop sequence MICROSOFTSEQDTPROPERTIES ;                                                                                                                                        
drop sequence MODIFIERGROUPIDSEQ ;                                                                                                                                              
drop sequence MODIFIERIDSEQ ;                                                                                                                                                   
drop sequence PACKAGEIDSEQ ;                                                                                                                                                    

drop sequence PARAMETERIDSEQ ;                                                                                                                                                  
drop sequence PAYREQIDSEQ ;                                                                                                                                                     
drop sequence PAYSETTLEMENTACTIONSEQ ;                                                                                                                                          
drop sequence PLSQL_PROFILER_RUNNUMBER ;                                                                                                                                        
drop sequence PROCESSIDSEQ ;                                                                                                                                                    
drop sequence PROCESSINSTANCEIDSEQ ;                                                                                                                                            
drop sequence PRODUCTATTRIBUTEIDSEQ ;                                                                                                                                           
drop sequence PRODUCTCONFLICTSEQ ;                                                                                                                                              
drop sequence PRODUCTEDITSEQ ;                                                                                                                                                  
drop sequence PRODUCTEXPORTSEQ ;                                                                                                                                                
drop sequence PRODUCTFAMILYIDSEQ ;                                                                                                                                              
drop sequence PRODUCTIDSEQ ;                                                                                                                                                    
drop sequence PRODUCTIMPORTSEQ ;                                                                                                                                                

drop sequence PROVISIONINGSYSTEMIDSEQ ;                                                                                                                                         
drop sequence PSGDSEVGCTRLFILESEQ ;                                                                                                                                             
drop sequence PSGDSEVGEVENTFILESEQ ;                                                                                                                                            
drop sequence PSGSUMMARYID ;                                                                                                                                                    
drop sequence RATINGCONFLICTSEQ ;                                                                                                                                               
drop sequence RATINGEDITSEQ ;                                                                                                                                                   
drop sequence RATINGEXPORTSEQ ;                                                                                                                                                 
drop sequence RATINGIMPORTSEQ ;                                                                                                                                                 
drop sequence RATINGTARIFFIDSEQ ;                                                                                                                                               
drop sequence RATINGTARIFFTYPEIDSEQ ;                                                                                                                                           
drop sequence REDEMPTIONOPTIONIDSEQ ;                                                                                                                                           
drop sequence RTFFILEGROUPSEQ ;                                                                                                                                                 
drop sequence SCHEDULEINSTANCEIDSEQ ;                                                                                                                                           

drop sequence SERVICEREQUESTTRANSSEQ ;                                                                                                                                          
drop sequence SETTLEMENTPERIODSEQ ;                                                                                                                                             
drop sequence SIBBMQUERYID ;                                                                                                                                                    
drop sequence STEPGROUPIDSEQ ;                                                                                                                                                  
drop sequence SUBSREFSEQ ;                                                                                                                                                      
drop sequence TARIFFIDSEQ ;                                                                                                                                                     
drop sequence TASKINSTANCEIDSEQ ;                                                                                                                                               
drop sequence THRESHREDEMPIDSEQ ;                                                                                                                                               
drop sequence TIMERATEDIARYIDSEQ ;                                                                                                                                              
drop sequence TIMERATEIDSEQ ;                                                                                                                                                   
drop sequence TOAD_SEQ ;                                                                                                                                                        
drop sequence TRANSFERIDSEQ ;                                                                                                                                                   
drop sequence USAGETYPEIDSEQ ;                                                                                                                                                  

drop sequence USTPRODUCTCLASSIDSEQ ;                                                                                                                                            

create sequence ACCOUNTNUMSEQ increment by 1 start with 108 nomaxvalue nocache;                                                                                                 
create sequence AEGSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                          
create sequence AQ$_COSTEDEVENTQUEUEHEAD_N increment by 1 start with 21 nomaxvalue nocache;                                                                                     
create sequence AQ$_COSTEDEVENTQUEUETAIL_N increment by 1 start with 21 nomaxvalue nocache;                                                                                     
create sequence AQ$_REJECTEVENTQUEUEHEAD_N increment by 1 start with 21 nomaxvalue nocache;                                                                                     
create sequence AQ$_REJECTEVENTQUEUETAIL_N increment by 1 start with 21 nomaxvalue nocache;                                                                                     
create sequence AUTHCODESEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                     
create sequence BANDINGMODELIDSEQ increment by 1 start with 39 nomaxvalue nocache;                                                                                              
create sequence BATCHIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                      
create sequence BILLDISCOUNTIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                               
create sequence BILLINGARCHIVEFILENUMSEQ increment by 1 start with 24 nomaxvalue nocache;                                                                                       
create sequence BILLINGCONFLICTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                              
create sequence BILLINGEDITSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                  

create sequence BILLINGEXPORTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                
create sequence BILLINGIMPORTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                
create sequence BONUSSCHEMEIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                
create sequence BUDGETPAYPLANIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                              
create sequence CCMANDATESEQ increment by 1 start with 100 nomaxvalue nocache;                                                                                                  
create sequence CHARGESEGMENTIDSEQ increment by 1 start with 28 nomaxvalue nocache;                                                                                             
create sequence COMPOSITEFILTERIDSEQ increment by 1 start with 23 nomaxvalue nocache;                                                                                           
create sequence CONVERGYSDPCVERIFICATION increment by 1 start with 43 nomaxvalue nocache;                                                                                       
create sequence COSTBANDIDSEQ increment by 1 start with 619 nomaxvalue nocache;                                                                                                 
create sequence COSTGROUPIDSEQ increment by 1 start with 1376 nomaxvalue nocache;                                                                                               
create sequence COSTINGRULESIDSEQ increment by 1 start with 26 nomaxvalue nocache;                                                                                              
create sequence CUSTOMERREFSEQ increment by 1 start with 117 nomaxvalue nocache;                                                                                                
create sequence DDMANDATESEQ increment by 1 start with 100000 nomaxvalue nocache;                                                                                               

create sequence DISPATCHAUDIT_SEQ increment by 1 start with 1256770 nomaxvalue nocache;                                                                                         
create sequence DLFBATCHSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                     
create sequence DUNNINGARCHIVEFILENUMSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                        
create sequence ECAINCIDENTGROUPSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                             
create sequence EVENTCLASSIDSEQ increment by 1 start with 83 nomaxvalue nocache;                                                                                                
create sequence EVENTDISCOUNTIDSEQ increment by 1 start with 233 nomaxvalue nocache;                                                                                            
create sequence EVENTFILTERIDSEQ increment by 1 start with 39 nomaxvalue nocache;                                                                                               
create sequence GC_PRODCUST10001SEQ increment by 1 start with 12615931 nomaxvalue nocache;                                                                                      
create sequence GC_PRODCUST10002SEQ increment by 1 start with 416601 nomaxvalue nocache;                                                                                        
create sequence GC_PRODCUST10003SEQ increment by 1 start with 479852 nomaxvalue nocache;                                                                                        
create sequence GC_PRODCUST10004SEQ increment by 1 start with 903969 nomaxvalue nocache;                                                                                        
create sequence GC_PRODCUST10005SEQ increment by 1 start with 305753 nomaxvalue nocache;                                                                                        
create sequence GC_PRODCUST10006SEQ increment by 1 start with 1457575 nomaxvalue nocache;                                                                                       

create sequence GC_PRODCUST10007SEQ increment by 1 start with 236334 nomaxvalue nocache;                                                                                        
create sequence GC_PRODCUST10008SEQ increment by 1 start with 2891 nomaxvalue nocache;                                                                                          
create sequence GC_PRODCUST10009SEQ increment by 1 start with 9384 nomaxvalue nocache;                                                                                          
create sequence GC_PRODCUST10014SEQ increment by 1 start with 21628 nomaxvalue nocache;                                                                                         
create sequence GC_PRODCUST10015SEQ increment by 1 start with 12520 nomaxvalue nocache;                                                                                         
create sequence ICEUNSETCARRYGROUPRUNIDSEQ increment by 1 start with 21 nomaxvalue nocache;                                                                                     
create sequence JOBIDSEQ increment by 1 start with 8287449 nomaxvalue nocache;                                                                                                  
create sequence LOCKVERSIONSEQ increment by 1 start with 465445 nomaxvalue nocache;                                                                                             
create sequence MANAGEDFILEIDSEQ increment by 1 start with 8241389 nomaxvalue nocache;                                                                                          
create sequence MICROSOFTSEQDTPROPERTIES increment by 1 start with 1 nomaxvalue nocache;                                                                                        
create sequence MODIFIERGROUPIDSEQ increment by 1 start with 21 nomaxvalue nocache;                                                                                             
create sequence MODIFIERIDSEQ increment by 1 start with 37892 nomaxvalue nocache;                                                                                               
create sequence PACKAGEIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                    

create sequence PARAMETERIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                  
create sequence PAYREQIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                     
create sequence PAYSETTLEMENTACTIONSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                          
create sequence PLSQL_PROFILER_RUNNUMBER increment by 1 start with 11 nomaxvalue nocache;                                                                                       
create sequence PROCESSIDSEQ increment by 1 start with 1120710 nomaxvalue nocache;                                                                                              
create sequence PROCESSINSTANCEIDSEQ increment by 1 start with 1514952 nomaxvalue nocache;                                                                                      
create sequence PRODUCTATTRIBUTEIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                           
create sequence PRODUCTCONFLICTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                              
create sequence PRODUCTEDITSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                  
create sequence PRODUCTEXPORTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                
create sequence PRODUCTFAMILYIDSEQ increment by 1 start with 5 nomaxvalue nocache;                                                                                              
create sequence PRODUCTIDSEQ increment by 1 start with 41 nomaxvalue nocache;                                                                                                   
create sequence PRODUCTIMPORTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                

create sequence PROVISIONINGSYSTEMIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                         
create sequence PSGDSEVGCTRLFILESEQ increment by 1 start with 11316 nomaxvalue nocache;                                                                                         
create sequence PSGDSEVGEVENTFILESEQ increment by 1 start with 11316 nomaxvalue nocache;                                                                                        
create sequence PSGSUMMARYID increment by 1 start with 72082 nomaxvalue nocache;                                                                                                
create sequence RATINGCONFLICTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                               
create sequence RATINGEDITSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                   
create sequence RATINGEXPORTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                 
create sequence RATINGIMPORTSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                 
create sequence RATINGTARIFFIDSEQ increment by 1 start with 433 nomaxvalue nocache;                                                                                             
create sequence RATINGTARIFFTYPEIDSEQ increment by 1 start with 12 nomaxvalue nocache;                                                                                          
create sequence REDEMPTIONOPTIONIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                           
create sequence RTFFILEGROUPSEQ increment by 1 start with 39 nomaxvalue nocache;                                                                                                
create sequence SCHEDULEINSTANCEIDSEQ increment by 1 start with 645126 nomaxvalue nocache;                                                                                      

create sequence SERVICEREQUESTTRANSSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                          
create sequence SETTLEMENTPERIODSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                             
create sequence SIBBMQUERYID increment by 1 start with 405 nomaxvalue nocache;                                                                                                  
create sequence STEPGROUPIDSEQ increment by 1 start with 20 nomaxvalue nocache;                                                                                                 
create sequence SUBSREFSEQ increment by 1 start with 104 nomaxvalue nocache;                                                                                                    
create sequence TARIFFIDSEQ increment by 1 start with 1301 nomaxvalue nocache;                                                                                                  
create sequence TASKINSTANCEIDSEQ increment by 1 start with 664296 nomaxvalue nocache;                                                                                          
create sequence THRESHREDEMPIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                               
create sequence TIMERATEDIARYIDSEQ increment by 1 start with 20 nomaxvalue nocache;                                                                                             
create sequence TIMERATEIDSEQ increment by 1 start with 33 nomaxvalue nocache;                                                                                                  
create sequence TOAD_SEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                        
create sequence TRANSFERIDSEQ increment by 1 start with 266588560 nomaxvalue nocache;                                                                                           
create sequence USAGETYPEIDSEQ increment by 1 start with 1 nomaxvalue nocache;                                                                                                  

create sequence USTPRODUCTCLASSIDSEQ increment by 1 start with 13 nomaxvalue nocache;        