spool cr_geneva_users.log

CREATE USER GENEVA_ADMIN  PROFILE DEFAULT 
    IDENTIFIED BY GENEVA_ADMIN DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP 
    ACCOUNT UNLOCK;
grant dba to geneva_admin with admin option;
GRANT SELECT ON SYS.DBA_PROFILES 	TO GENEVA_ADMIN;
GRANT SELECT ON SYS.DBA_ROLES 		TO GENEVA_ADMIN;
GRANT SELECT ON SYS.DBA_ROLE_PRIVS 	TO GENEVA_ADMIN;
GRANT SELECT ON SYS.DBA_TABLESPACES TO GENEVA_ADMIN;
GRANT SELECT ON SYS.DBA_TAB_PRIVS 	TO GENEVA_ADMIN;
GRANT SELECT ON SYS.DBA_USERS 		TO GENEVA_ADMIN;
GRANT CONNECT TO GENEVA_ADMIN;
@createrole.sql
@roleprivs.sql

CREATE USER GENEVAADMINUSER  PROFILE DEFAULT 
    IDENTIFIED BY genevauser DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP 
    ACCOUNT UNLOCK;
GRANT CONNECT TO GENEVAADMINUSER;
GRANT GENEVAADMIN TO  GENEVAADMINUSER;

CREATE USER SECURITY PROFILE DEFAULT
    IDENTIFIED BY genevauser DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK;
GRANT CONNECT TO SECURITY;
GRANT GENEVASECURITY TO SECURITY;
@securityrole.sql
@securityprivs.sql

CREATE USER GENEVABATCHUSER PROFILE DEFAULT
    IDENTIFIED BY GENEVABATCHUSER DEFAULT TABLESPACE DATA
    TEMPORARY TABLESPACE TEMP
    ACCOUNT UNLOCK;
GRANT CONNECT TO GENEVABATCHUSER;
GRANT GENEVABATCH TO GENEVABATCHUSER;

connect GENEVA_ADMIN/GENEVA_ADMIN
rem @/Disk1/app/geneva/product/geneva-5.1.23.t9i2/schema/install/migrationprocess.sql
rem @/Disk1/app/geneva/product/geneva-5.1.23.t9i2/schema/install/gnvschema.spc
rem @/Disk1/app/geneva/product/geneva-5.1.23.t9i2/schema/install/gnvschema.plb

spool off
